name: Testes Agendados - a cada 2 horas seg-sexta


on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */2 * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional


      - name: Execucao dos Testes Agendados
        run: mvn test -Dcucumber.filter.tags="@regressivo" cluecumber-report:reporting

      - name: Relatorio de Execucao
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar Relatorio
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/report/"

      - name: Enviar Notificacao Slack - Sucesso
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: regressivos
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://www.clipartkey.com/mpngs/m/283-2836740_success-icon-transparent-green-success-png-icon.png
            SLACK_MESSAGE: 'Teste AGENDADO executado com sucesso! :white_check_mark:'
            SLACK_TITLE: 'Teste AGENDADO executado com sucesso! :white_check_mark:'
            SLACK_USERNAME: SUCESSO

      - name: Enviar Notificacao Slack - Falha
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: regressivos
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://flyclipart.com/thumb2/fail-failed-lock-icon-with-png-and-vector-format-for-free-745392.png
          SLACK_MESSAGE: 'Erro ao executar teste AGENDADO! :fire:'
          SLACK_TITLE: 'Erro ao executar teste AGENDADO! :fire:'
          SLACK_USERNAME: ERRO
