name: Testes Regressivos

on:
  pull_request:
    branches: [ main ]

jobs:
  RunTest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          

      - name: Execucao dos Testes
        run: mvn test -Denv=uat.properties -Dcucumber.filter.tags="@regressivo"

      - name: Relatorio dos Testes
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Upload Relatorio dos Testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-execution
          path: "**/report/"

      - name: Implantar Resultados no Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "**/report/index.html"

      - name: Enviar Notificacao Slack - Sucesso
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: regressivos
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.clipartkey.com/mpngs/m/283-2836740_success-icon-transparent-green-success-png-icon.png
          SLACK_MESSAGE: 'Teste do PR executado com sucesso! :white_check_mark:'
          SLACK_TITLE: 'Teste do PR executado com sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar Notificacao Slack - Falha
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: regressivos
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://flyclipart.com/thumb2/fail-failed-lock-icon-with-png-and-vector-format-for-free-745392.png
          SLACK_MESSAGE: 'Erro ao executar testes do PR! :fire:'
          SLACK_TITLE: 'Erro ao executar testes do PR! :fire:'
          SLACK_USERNAME: ERRO