name: Testes Agendados


on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional


      - name: Execucao dos Testes Regressivos
        run: mvn test -Dcucumber.filter.tags="@regressivo" cluecumber-report:reporting

      - name: Relatorio de Execucao
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar Relatorio
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/report/"
